import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js-Aaryan",
    template: "%s - Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "red",
            padding: "20px",
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "blue",
            padding: "20px",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
